title=RuneScape
codebase=http://world1.aethryadnd.online/
initial_class=client.class
initial_jar=gamepack.jar
lobbyaddress=lobby.aethryadnd.online
serverlist=http://config.aethryadnd.online/serverlist.ws
window_preferredwidth=1024
window_preferredheight=768
adverturl=http://www.runescape.com/g=runescape/bare_advert.ws